version: "3"

services:
  postgres:
    image: postgres
#    volumes:
#      - \src\main\resources\migrations\db\V1__create_account_table.sql
#      - ./02-basegeografica.sql:/docker-entrypoint-initdb.d/02-basegeografica.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"